### ISSUE TITLE
Group capstone: set up  Kanban board

### ISSUE THREAD

**Issue by Rudy-Menekam** [Rudy-Menekam/Javascript-Capstone-project#21]
Link to our GitHub project
 -https://github.com/Rudy-Menekam/Javascript-Capstone-project/projects/1

Our group is made up of two participants: Student A and B

**Comment by Ibizugbe** [comment]
Hi Team👋👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that links to an empty repository. kindly provide the link to your github project as [required](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md) and resubmit for a review👍
<img width="957" alt="emptyyy" src="https://user-images.githubusercontent.com/64643995/218424200-03e2449e-8223-4946-a8a1-7a109cdc8d86.png">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by pinkmoon25** [comment]
Hi @Rudy-Menekam & @alicemirigo92 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
Kanban setup :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
